name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 

    - name: Set up Node.js
      uses: actions/setup-node@v3 
      with:
        node-version: '16' 

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t weather_image .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push guylainekamdem/weather_image:latest

    - name: Deploy to production
      run: |
        ssh user@123.456.789.123 "docker pull yourusername/weather_image:latest &&
        docker stop weather_container &&
        docker rm weather_container &&
        docker run -d --name=weather_container -p 3500:3500 -e LAT='31.2504' -e LONG='-99.2506' yourusername/weather_image:latest"
